theme: minima
show_excerpts: true
hide_site_feed_link: true
minima:
  style: dark
nav_pages:
  - about.md
social_links:
  - title: Deployment Live repository at GitHub
    icon: github
    url: "https://github.com/deploymentLive"
  - title: Keith on Linked In
    icon: linkedin
    url: "https://www.linkedin.com/in/keith-garner-47471924/"  

